"""create_student_and_junction_tables

Revision ID: 7368c9a70003
Revises: 66f7810814b8
Create Date: 2026-06-24 16:14:55.267175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7368c9a70003'
down_revision: Union[str, None] = '66f7810814b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nickname', sa.String(length=100), nullable=True),
    sa.Column('dob', sa.DateTime(), nullable=True),
    sa.Column('contact', sa.String(length=50), nullable=True),
    sa.Column('position', sa.String(length=100), nullable=True),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('date_joined', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mentor_students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mentor_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['mentor_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(op.f('fk_users_admin_id'), 'users', type_='foreignkey')
    op.drop_constraint(op.f('fk_users_mentor_id'), 'users', type_='foreignkey')
    op.drop_column('users', 'mentor_id')
    op.drop_column('users', 'admin_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('admin_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('mentor_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_users_mentor_id'), 'users', 'users', ['mentor_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_users_admin_id'), 'users', 'users', ['admin_id'], ['id'], ondelete='SET NULL')
    op.drop_table('mentor_students')
    op.drop_table('admin_students')
    op.drop_table('students')
    # ### end Alembic commands ###
