"""add_assignment_and_approval_to_users

Revision ID: 8c8ea677e405
Revises: f470e66cf66e
Create Date: 2026-06-24 15:46:39.434469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c8ea677e405'
down_revision: Union[str, None] = 'f470e66cf66e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_approved', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('users', sa.Column('mentor_id', sa.Uuid(), nullable=True))
    op.add_column('users', sa.Column('admin_id', sa.Uuid(), nullable=True))
    op.create_foreign_key('fk_users_admin_id', 'users', 'users', ['admin_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_users_mentor_id', 'users', 'users', ['mentor_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_users_mentor_id', 'users', type_='foreignkey')
    op.drop_constraint('fk_users_admin_id', 'users', type_='foreignkey')
    op.drop_column('users', 'admin_id')
    op.drop_column('users', 'mentor_id')
    op.drop_column('users', 'is_approved')
    # ### end Alembic commands ###
